import type { Metadata } from "next";
import { Roboto } from "@next/font/google"
import "../styles/global.scss"
import { Header } from "@/components/header";
import AuthProvider from "./_providers/auth";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700', '900']
})

export const metadata: Metadata = {
  title: "ig.news",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel='shortcut icon' href='/favicon.png' type='image/x-icon' />
      </head>
      <body
        className={roboto.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>

      </body>
    </html>
  );
}
